# Generated by Django 5.2.1 on 2025-05-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0002_borrowrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
