# Generated by Django 5.2.1 on 2025-05-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0003_borrowrequest_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
