# Generated by Django 5.2.1 on 2025-05-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0004_borrowrequest_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='planned_borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='planned_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
