# Generated by Django 5.2.1 on 2025-05-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0006_borrowrequest_returned_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='unreturned_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Return'), ('lost', 'Lost'), ('damage', 'Damage')], max_length=20, null=True),
        ),
    ]
