# Generated by Django 5.2.1 on 2025-05-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0007_alter_borrowrequest_unreturned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='item_conditions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='resolution_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='unreturned_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Return'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('replaced', 'Replaced'), ('paid', 'Paid')], max_length=20, null=True),
        ),
    ]
