# Generated by Django 5.2.1 on 2025-05-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0008_borrowrequest_item_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appliance_images/'),
        ),
    ]
